import json
import cpp


# Get interop_example file and object

# SET CONSTANTS
def main():
    # Abhi's constants
    constAlt = 120
    cameraWidth = 130
    inputFile = "../../../mission_plan/interop_example.json"
    
    # Paul's constants
    
    # interop_example points    
    interop_example_file = open(inputFile, "r")
    
    interop_example_obj = json.load(interop_example_file)
    interop_example_file.close()
    
    interop_points = interop_example_obj["waypoints"]
    
    # 1. Run Abhi Coverage Path Plannign on interop example file
    
    abhiPts = cpp.runProgram(constAlt, cameraWidth, inputFile)
    
    searchpoints_file = open("searchpath.json", "r")
    searchpoints_obj = json.load(searchpoints_file)
    searchpoints_file.close()
    wayPts = searchpoints_obj
    
    # 2. Run Paul Landing
    
    paulPts = []
    
    # Grab Dictionary Generated by (1) (2), dump into third dictionary
    
    outputDict = []
    outputDict.extend(interop_points)
    outputDict.extend(abhiPts)
    outputDict.extend(paulPts)
    
    
    interop_example_obj["waypoints"].extend(abhiPts)
    
    # Write dicitonary to JSON
    
    interop_output_file = open("interop_output.json", "w")
    json.dump(interop_example_obj, interop_output_file)
    interop_output_file.close()
